### ISSUE TITLE
Reason for removal of hotTrendsDetail()?

### ISSUE THREAD

**Issue by Darkspine77** [pat310/google-trends-api#81]
Hi, I was just wondering as to why the hotTrendsDetail method was removed and if there is a replacement. Is there a way to get the most popular google searches in the new version of the module? 

Thanks

**Comment by pat310** [comment]
Hello @Darkspine77! I removed it because some of the API methods had severe quota restrictions and the library was more of a random mix of url calls that returned various data (for example, rather than returning JSON, some of the calls returned XML like `hotTrendsDetail`). You can use the [old code](https://github.com/pat310/google-trends-api/blob/ea74330e95e6d55d9cf86dd94a65fa9a53f9b612/src/utils/hotTrendsDetail.js) for the `hotTrendsDetail` method if you want. Essentially you will want to use this url: `http://www.${obj.countryDomain}/trends/hottrends/atom/feed` where `${obj.countryDomain}` is from the [mapToDomain](https://github.com/pat310/google-trends-api/blob/ea74330e95e6d55d9cf86dd94a65fa9a53f9b612/src/resources/countryCodes.js) object. Here is an example for the US: `https://trends.google.com/trends/hottrends/atom/feed`.

I don't think there is a way to get the most popular google searches with the current implementation of the library, but I could definitely look into it. Are you looking for something similar to the information provided at [top charts](https://trends.google.com/trends/topcharts)?

**Comment by pat310** [comment]
I'm going to close this for now as there doesn't seem to be much interest
